require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PhotosController do

  def mock_photo(stubs={})
    @mock_photo ||= mock_model(Photo, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all photo ids as @id_list" do
      Photo.stub(:sorted) { [mock_photo] }
      get :index
      assigns(:id_list).should eq({'id_list' => [mock_photo.id]})
    end
  end

  describe "GET show" do
    it "assigns the requested photo as @photo" do
      Photo.stub(:find).with("37") { mock_photo }
      get :show, :id => "37"
      assigns(:photo).should be(mock_photo)
    end
  end

end
